### ISSUE TITLE
Target not found: wireguard-arch

### ISSUE THREAD

**Issue by phunni** [hunger/cleanroom#1]
First github issue :-)

Have set up a new (but not at all new) machine which I'm hoping will serve as a build server and am currently just trying to get clrm build system-example again and will then document the process - including required packages.

Anyway - the build fails during type-bootable with:

```
++++++ Arguments  : /usr/bin/pacman --config /home/paul/base/work/scratch/meta/pacman/pacman.conf --root /home/paul/base/work/scratch/fs --cachedir /home/paul/base/work/scratch/cache/pacman --dbpath /home/paul/base/work/scratch/meta/pacman/db --hookdir /home/paul/base/work/scratch/meta/pacman/hooks --logfile /home/paul/base/work/scratch/cache/pacman/log --gpgdir /home/paul/base/work/scratch/meta/pacman/gpg --noconfirm -S --needed linux linux-firmware ipw2100-fw ipw2200-fw alsa-firmware btrfs-progs dosfstools squashfs-tools iputils iproute2 cryptsetup lvm2 mdadm efibootmgr pciutils sed tar usbutils wireguard-arch wireguard-tools 
++++++ Return Code: 1 
++++++ StdOut     : 
++++++ StdErr     : 
++++++     warning: cryptsetup-2.3.1-1 is up to date -- skipping 
++++++     warning: sed-4.8-1 is up to date -- skipping 
++++++     error: target not found: wireguard-arch 
++++++      
 FAIL  Generation of "type-bootable" failed: Error: Unexpected return value 1 (expected 0). 

>>>>>> End of Buffer <<<<<<


Traceback Information:
  File "/home/paul/cleanroom/cleanroom/generator.py", line 90, in generate_systems
    exe.run(system_name, base_system_name, exec_obj_list,
  File "/home/paul/cleanroom/cleanroom/executor.py", line 51, in run
    command.execute_func(exec_obj.location, system_context,
  File "/home/paul/cleanroom/cleanroom/commandmanager.py", line 102, in <lambda>
    __execute_func(command, loc, sc, *args, **kwargs))
  File "/home/paul/cleanroom/cleanroom/commandmanager.py", line 89, in __execute_func
    command(location, system_context, *args, **kwargs)
  File "/home/paul/cleanroom/cleanroom/commands/pacman.py", line 38, in __call__
    pacman(system_context, *args,
  File "/home/paul/cleanroom/cleanroom/helper/archlinux/pacman.py", line 237, in pacman
    _run_pacman(system_context, *action, *packages,
  File "/home/paul/cleanroom/cleanroom/helper/archlinux/pacman.py", line 151, in _run_pacman
    run(pacman_command, *all_args,
  File "/home/paul/cleanroom/cleanroom/helper/run.py", line 106, in run
    raise GenerateError('Unexpected return value {} (expected {}).'


>>>>>> END OF ERROR REPORT <<<<<<
Traceback (most recent call last):
  File "/home/paul/cleanroom/cleanroom/generator.py", line 90, in generate_systems
    exe.run(system_name, base_system_name, exec_obj_list,
  File "/home/paul/cleanroom/cleanroom/executor.py", line 51, in run
    command.execute_func(exec_obj.location, system_context,
  File "/home/paul/cleanroom/cleanroom/commandmanager.py", line 102, in <lambda>
    __execute_func(command, loc, sc, *args, **kwargs))
  File "/home/paul/cleanroom/cleanroom/commandmanager.py", line 89, in __execute_func
    command(location, system_context, *args, **kwargs)
  File "/home/paul/cleanroom/cleanroom/commands/pacman.py", line 38, in __call__
    pacman(system_context, *args,
  File "/home/paul/cleanroom/cleanroom/helper/archlinux/pacman.py", line 237, in pacman
    _run_pacman(system_context, *action, *packages,
  File "/home/paul/cleanroom/cleanroom/helper/archlinux/pacman.py", line 151, in _run_pacman
    run(pacman_command, *all_args,
  File "/home/paul/cleanroom/cleanroom/helper/run.py", line 106, in run
    raise GenerateError('Unexpected return value {} (expected {}).'
cleanroom.exceptions.GenerateError: Error: Unexpected return value 1 (expected 0).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paul/cleanroom/clrm", line 13, in <module>
    main.run()
  File "/home/paul/cleanroom/cleanroom/main.py", line 72, in run
    main(*sys.argv)
  File "/home/paul/cleanroom/cleanroom/main.py", line 139, in main
    generator.generate_systems(work_directory=work_directory,
  File "/home/paul/cleanroom/cleanroom/generator.py", line 93, in generate_systems
    self._report_error(system_name, e, ignore_errors=ignore_errors)
  File "/home/paul/cleanroom/cleanroom/generator.py", line 40, in _report_error
    self._report_error_details(system, exception,
  File "/home/paul/cleanroom/cleanroom/generator.py", line 57, in _report_error_details
    raise GenerateError('Generation failed.',
cleanroom.exceptions.GenerateError: Error: Generation failed.
    Trigger: Error: Unexpected return value 1 (expected 0).

```
Not a complete surprise since wireguard-arch seems to be q virtual package. I don't know if that 'a new thing or...?
I'm currently running a build with that package omitted from the list. Will update with how that goes.

**Comment by phunni** [comment]
type-bootable now built - so that package just needs removing from the list
