### ISSUE TITLE
All builds fail with Assertion error

### ISSUE THREAD

**Issue by phunni** [hunger/cleanroom#2]
I'm honestly not sure what I've done, although I have exported the base directory as an NFS share in anticipation of future system updates. All my builds now fail with the following error:

```
Traceback (most recent call last):
  File "/home/paul/cleanroom/clrm", line 13, in <module>
    main.run()
  File "/home/paul/cleanroom/cleanroom/main.py", line 72, in run
    main(*sys.argv)
  File "/home/paul/cleanroom/cleanroom/main.py", line 127, in main
    with WorkDir(btrfs_helper,
  File "/home/paul/cleanroom/cleanroom/workdir.py", line 71, in __init__
    if not umount_all(work_directory):
  File "/home/paul/cleanroom/cleanroom/helper/mount.py", line 71, in umount_all
    umount(mp)
  File "/home/paul/cleanroom/cleanroom/helper/mount.py", line 58, in umount
    assert len(mount_points(directory)) == 1
AssertionError
```

**Comment by hunger** [comment]
Where did you mount the NFS share?

That assert is to make sure something is actually mounted on the directory it will try to unmount right after the assert. The assert should trigger if:
 * Nothing is mounted there -- you would not need to unmount then.
 * Several things are mounted over each other -- which I can not think of a valid use case.

Can you run mount | grep "/path/to/workdir" for me, please, so we can see which of the two it is?
